# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  workflow_dispatch:
  push:
    branches: [ "yo2" ]
  pull_request:
    branches: [ "yo2" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build zbe_multi_lv16_sp22_hagane_atk106_def86
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target zbe_multi_lv16_sp22_hagane_atk106_def86
    - name: Build zbe_multi_lv13_sp13_hagane_atk101
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target zbe_multi_lv13_sp13_hagane_atk101

    - name: echo SHA256 zbe_multi_lv16_sp22_hagane_atk106_def86
      run: Get-FileHash -Algorithm SHA256 -Path "${{github.workspace}}/build/${{env.BUILD_TYPE}}/zbe_multi_lv16_sp22_hagane_atk106_def86.exe"
    - name: echo SHA256 zbe_multi_lv13_sp13_hagane_atk101
      run: Get-FileHash -Algorithm SHA256 -Path "${{github.workspace}}/build/${{env.BUILD_TYPE}}/zbe_multi_lv13_sp13_hagane_atk101.exe"

    - name: Copy License file
      run: Copy-Item -Path "${{github.workspace}}/LICENSE" -Destination "${{github.workspace}}/build/${{env.BUILD_TYPE}}/"

    - name: Copy image folder
      run: |
        Copy-Item -Path "${{github.workspace}}/image" `
                  -Destination "${{github.workspace}}/build/${{env.BUILD_TYPE}}/image" `
                  -Recurse

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: rbe
        path: |
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/zbe_multi_lv16_sp22_hagane_atk106_def86.exe
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/zbe_multi_lv13_sp13_hagane_atk101.exe
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/zbe_multi_lv16_sp22_hagane_atk106_def86.pdb
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/zbe_multi_lv13_sp13_hagane_atk101.pdb
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/LICENSE
          ${{github.workspace}}/build/${{env.BUILD_TYPE}}/image/**
